

CREATE TABLE public.categories (
                                   id integer NOT NULL,
                                   nom character varying(255) NOT NULL
);



ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.clients (
                                id bigint NOT NULL,
                                email character varying(255) NOT NULL,
                                nom character varying(255) NOT NULL,
                                points_fidelite integer,
                                telephone character varying(255)
);



ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.produits (
                                 id bigint NOT NULL,
                                 description character varying(255),
                                 nom character varying(255),
                                 prix_unitaire double precision,
                                 seuil_alerte integer,
                                 categorie_id integer,
                                 stock integer
);



ALTER TABLE public.produits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.ref_statuts_rdv (
                                        id bigint NOT NULL,
                                        code character varying(255),
                                        libelle character varying(255)
);



ALTER TABLE public.ref_statuts_rdv ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ref_statuts_rdv_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.rendez_vous (
                                    id bigint NOT NULL,
                                    date_heure timestamp(6) without time zone,
                                    client_id bigint,
                                    statut_id bigint
);



ALTER TABLE public.rendez_vous ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rendez_vous_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.produits
    ADD CONSTRAINT produits_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.ref_statuts_rdv
    ADD CONSTRAINT ref_statuts_rdv_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT rendez_vous_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.ref_statuts_rdv
    ADD CONSTRAINT ukdjihu1lu4ren3b9hc5u4mc7oi UNIQUE (code);



ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uksrv16ica2c1csub334bxjjb59 UNIQUE (email);



ALTER TABLE ONLY public.produits
    ADD CONSTRAINT fk8xk7p0dnnygs2sys4thsfekba FOREIGN KEY (categorie_id) REFERENCES public.categories(id);



ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT fkf9m53qi8tm8wkd4k6i8ag12jp FOREIGN KEY (client_id) REFERENCES public.clients(id);



ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT fkokukayi7r0kb4q3h3jdi04i2n FOREIGN KEY (statut_id) REFERENCES public.ref_statuts_rdv(id);




INSERT INTO public.categories (id, nom) VALUES
                                            (1, 'Services'),
                                            (2, 'Produits'),
                                            (3, 'Coiffure'),
                                            (4, 'Soin du corps'),
                                            (5, 'Maquillage');

INSERT INTO public.clients (id, email, nom, points_fidelite, telephone) VALUES
                                                                            (2, 'marie.curie@email.com', 'Marie Curie', 50, '0607080910'),
                                                                            (3, 'test@test.com', 'test testons', 0, '0123456789'),
                                                                            (1, 'jean.dupont@email.com', 'Jean Dupont', 10, '0102030405');
INSERT INTO public.produits (id, description, nom, prix_unitaire, seuil_alerte, categorie_id, stock) VALUES
                                                                                                         (1, 'Pour cheveux secs', 'Shampoing Hydratant', 15.5, 5, 1, NULL),
                                                                                                         (4, 'Format professionnel', 'Laque Fixation', 12.5, 5, 1, NULL);
INSERT INTO public.ref_statuts_rdv (id, code, libelle) VALUES
                                                           (1, 'PENDING', 'En attente'),
                                                           (2, 'CONFIRME', 'Confirmé'),
                                                           (3, 'HONORE', 'Honoré'),
                                                           (4, 'ANNULE', 'Annulé');

INSERT INTO public.rendez_vous (id, date_heure, client_id, statut_id) VALUES
    (1, '2026-05-11 12:54:00', 1, 1);


SELECT pg_catalog.setval('public.categories_id_seq', 5, true);

SELECT pg_catalog.setval('public.clients_id_seq', 3, true);



SELECT pg_catalog.setval('public.produits_id_seq', 5, true);




SELECT pg_catalog.setval('public.ref_statuts_rdv_id_seq', 4, true);



SELECT pg_catalog.setval('public.rendez_vous_id_seq', 2, true);

